name: CI

on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
#          - name: "Test: Python 3.7"
#            python: "3.7"
#            tox: py37
#          - name: "Test: Python 3.8"
#            python: "3.8"
#            tox: py38
          - name: "Test: Python 3.9"
            python: "3.9"
            tox: py39
            coverage: true
          - name: "Lint: flake8"
            python: "3.9"
            tox: flake8

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox pytest pytest-cov flake8
      - run: python -m tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
        env:
          TEST_BANDCAMP_ID: ${{ secrets.BANDCAMP_IDENTITY }}
      - run: python -m tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
        env:
          TEST_BANDCAMP_ID: ${{ secrets.BANDCAMP_IDENTITY }}
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
